//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use std::sync::Arc;
use async_trait::async_trait;
use essential_data::sequence_generator::{GeneratorDispatcher, LegacyHiloGenerator};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use crate::sequence_generator::IdGenerator;
#[cfg(feature = "redis")]
use redis_macros::{FromRedisValue, ToRedisArgs};
#[cfg(feature = "redis")]
use essential_data::active_store::{ActiveStore, StoreValue};

#[derive(Debug, PartialEq, Eq, Hash, Clone, EnumIter, DeriveActiveEnum, Default, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(Some(15))")]
#[allow(non_camel_case_types)]
pub enum PromoTransactionDesc {
    #[default]
    #[sea_orm(string_value = "PROMO_IN")]
    PROMO_IN,
    #[sea_orm(string_value = "PROMO_OUT")]
    PROMO_OUT,
    #[sea_orm(string_value = "PROMO_EXPIRE")]
    PROMO_EXPIRE,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Default)]
#[sea_orm(table_name = "promo_transaction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub amount: i32,
    pub balance: i32,
    pub description: Option<PromoTransactionDesc>,
    #[sea_orm(unique, column_name = "externalid")]
    pub external_id: Option<String>,
    #[sea_orm(column_name = "timedone")]
    pub time_done: Option<DateTime>,
    pub account_id: Option<i64>,
    pub author_id: Option<i64>,
    pub multi: i32,
    pub round_id: Option<i64>,
    pub expire: Option<DateTime>,
    pub offer_id: Option<Uuid>,
    pub charge_id: Option<String>,
    pub stake: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::promo_account::Entity",
        from = "Column::AccountId",
        to = "super::promo_account::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Account,
    #[sea_orm(
        belongs_to = "essential_data::user_user::Entity",
        from = "Column::AuthorId",
        to = "essential_data::user_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::common_round::Entity",
        from = "Column::RoundId",
        to = "super::common_round::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Round,
}

impl Related<super::promo_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<essential_data::user_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

/*impl Related<super::fugaso_round::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Round.def()
    }
}*/

impl ActiveModelBehavior for ActiveModel {}

#[async_trait]
impl<G: IdGenerator + Send + Sync> GeneratorDispatcher<G> for Model {
    async fn call(s: &G) -> Result<i64, DbErr> {
        s.gen_promo_transaction().await
    }
}

pub fn create_sequence(pool: Arc<DatabaseConnection>) -> LegacyHiloGenerator {
    LegacyHiloGenerator::new(
        "promo_transaction_sequence",
        49,
        pool,
    )
}

#[cfg(feature = "redis")]
#[derive(Debug, DeriveIntoActiveModel, Default, Clone, Serialize, Deserialize, FromRedisValue, ToRedisArgs)]
pub struct StoreModel {
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub id: StoreValue<i64>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub amount: StoreValue<i32>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub balance: StoreValue<i32>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub description: StoreValue<Option<PromoTransactionDesc>>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub external_id: StoreValue<Option<String>>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub time_done: StoreValue<Option<DateTime>>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub account_id: StoreValue<Option<i64>>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub author_id: StoreValue<Option<i64>>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub multi: StoreValue<i32>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub round_id: StoreValue<Option<i64>>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub expire: StoreValue<Option<DateTime>>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub offer_id: StoreValue<Option<Uuid>>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub charge_id: StoreValue<Option<String>>,
    #[serde(skip_serializing_if = "StoreValue::is_none", default)]
    pub stake: StoreValue<i64>,
}

#[cfg(feature = "redis")]
impl ActiveStore for ActiveModel {
    type R = StoreModel;

    fn to_active_store(self) -> Self::R {
        StoreModel {
            id: self.id.into(),
            amount: self.amount.into(),
            balance: self.balance.into(),
            description: self.description.into(),
            external_id: self.external_id.into(),
            time_done: self.time_done.into(),
            account_id: self.account_id.into(),
            author_id: self.author_id.into(),
            multi: self.multi.into(),
            round_id: self.round_id.into(),
            expire: self.expire.into(),
            offer_id: self.offer_id.into(),
            charge_id: self.charge_id.into(),
            stake: self.stake.into(),
        }
    }
}